import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  JetBrains_Mono,
  Space_Mono,
} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/layouts/Container";

const jetBrainMono = JetBrains_Mono({
  variable: "--font-jetBrain-mono",
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-space-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.variable} ${jetBrainMono.variable} antialiased`}
      >
        <Navbar />
        <Container>
          <div className="border py-7 mt-5 px-10 border-[#6A727E] rounded-md">{children}</div>
        </Container>
      </body>
    </html>
  );
}
